name: ffloat_example
description: Demonstrates how to use the ffloat plugin.
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.3
  fbutton: ^1.0.4
  ffloat:
    path: ../
  flutter:
    sdk: flutter
  fradio: ^1.0.1
  fsuper: ^0.1.5
  fswitch: ^1.1.2

dependency_overrides: {}

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/
  uses-material-design: true
